### PR TITLE
[Utopia 673] [Frontend] AutoSave functionality + PIA form refactor

### PR DESCRIPTION
**Pull request by kushal-arora-fw**
# Description

This PR includes the following proposed change(s):

- AutoSave functionality added to FE
- PIA form refactor
- Affected areas refactor

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Development Dependency Working Agreement
- [x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [ ] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [ ] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [ ] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [ ] N/A
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [x] My code follows Airbnb React Style Guidelines

## API Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [ ] New and existing unit tests pass locally with my changes
- [ ] My changes includes Swagger documentation updates that reflect the changes I am introducing

## Definition of Done

Definition of Done

### CODE REVIEW

**Comment by binggaofw** [comment]
when trying to create a new pia, just type the title and stop, it shows this banner, the message looks  
Screen Shot 2023-01-30 at 12 49 05 PM

**Comment by binggaofw** [comment]
sorry, click the wrong button to close the pr, reopen it

**Comment by binggaofw** [comment]
the design shows the title is red color not black, also missing the icon of the warning question mark 
please see here 
https://www.figma.com/file/fOpgpUVOEwp0CK48m7f8qB/Wireframes?node-id=3169%3A20038&t=aa19ZLXIcgcxlwDg-0

Screen Shot 2023-01-30 at 1 18 10 PM

**Comment by binggaofw** [comment]
maybe not related to this ticket, but we do not have breadcrumb for this page. @Bottle7  do we have a bug ticket for this issue?
Screen Shot 2023-01-30 at 1 23 13 PM

**Comment by binggaofw** [comment]
By the way, how to trigger multiple user conflict  modal, the design link
https://www.figma.com/file/fOpgpUVOEwp0CK48m7f8qB/Wireframes?node-id=3169%3A19066&t=lfRJZtMJ4AY7FJCU-0

**Review by binggaofw — APPROVED** [review]

**Review by antsand — APPROVED** [review]

**Pull request merged**
