### PR TITLE
[Utopia 443] [Documentation] Puppeteer for PDF

### PR DESCRIPTION
**Pull request by kushal-arora-fw**
# Description

This PR includes the following proposed change(s):

- Includes documentation for using Puppeteer for PDF
- Include ADR template

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

N/A

## Development Dependency Working Agreement
- [x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [ ] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [ ] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [ ] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [ ] My code follows Airbnb React Style Guidelines

## API Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [ ] New and existing unit tests pass locally with my changes
- [ ] My changes includes Swagger documentation updates that reflect the changes I am introducing

### CODE REVIEW

**Comment by binggaofw** [comment]
should we put all docs under docs folder ?

**Review by akroon3r — APPROVED** [review]
This is awesome. I'd like you to demo this template and the first ADR at our meeting today at 10am if possible.

**Comment by akroon3r** [comment]
> should we put all docs under docs folder ?

potentially we could nest it .github/wiki/adr or something like that?

**Review by antsand — APPROVED** [review]
we may need to profile the speed of puppeteer over time. But I doubt DPIA is going to have too many concurrent connections to seriously consider profiling. 

Good Job!

**Pull request merged**
