### PR TITLE
[UTOPIA-561]add backend search endpoint to support search by title or drafter name

### PR DESCRIPTION
**Pull request by binggaofw**
# Description

This PR includes the following proposed change(s):

- add search endpoint to support search by title or drafter name

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Development Dependency Working Agreement
- [x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [ ] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [ ] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [ ] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [ ] My code follows Airbnb React Style Guidelines

## API Development Changes
- [ ] N/A
- [x] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [x] New and existing unit tests pass locally with my changes
- [x] My changes includes Swagger documentation updates that reflect the changes I am introducing

## Definition of Done

Definition of Done

### CODE REVIEW

**Comment by akroon3r** [comment]
labeller works again 🚀

**Comment by akroon3r** [comment]
Function search has 32 lines of code (exceeds 25 allowed). Consider refactoring.

Do we need to amend this rule on code climate?

**Comment by binggaofw** [comment]
@akroon3r  I think this rule should change to allow 100 lines. 25 is too short for a function.
@Bottle7  @antsand what is your opinion ?

**Review by Bottle7 — APPROVED** [review]
Works fantastically!

**Comment by Bottle7** [comment]
> @akroon3r I think this rule should change to allow 100 lines. 25 is too short for a function. @Bottle7 @antsand what is your opinion ?

100 may be slightly to large but 25 is definitely too small so I am in agreement for an increase. Do we have an idea of what our average function size is?

**Comment by akroon3r** [comment]
> > @akroon3r I think this rule should change to allow 100 lines. 25 is too short for a function. @Bottle7 @antsand what is your opinion ?
> 
> 100 may be slightly to large but 25 is definitely too small so I am in agreement for an increase. Do we have an idea of what our average function size is?

find out and @ me in the war room and I'll make the change. The code climate action isn't blocking merging but 25 seems heinously low in my opinion.

**Comment by Bottle7** [comment]
100 lines looks like it may actually be appropriate. I'm seeing multiple functions hovering around 70-80, and that's only the frontend.

**Review by antsand — APPROVED** [review]

**Pull request merged**
