### PR TITLE
Adding bootstrap from CDN and not npm

### PR DESCRIPTION
**Pull request by antsand**
# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Development Dependency Working Agreement
- [ ] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [x] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [ ] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [x] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [ ] N/A
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [ ] My code follows Airbnb React Style Guidelines

## API Development Changes
- [ ] N/A
- [ ] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [ ] New and existing unit tests pass locally with my changes
- [ ] My changes includes Swagger documentation updates that reflect the changes I am introducing

### CODE REVIEW

**Review by kushal-arora-fw — COMMENTED** [review]
This change is interesting. Wondering why do we need CDN vs bundled in the app 🤔 Is it the bundle size we are worried of? Just want to understand the thought process.

**Comment by antsand** [comment]
> This change is interesting. Wondering why do we need CDN vs bundled in the app 🤔 Is it the bundle size we are worried of? Just want to understand the thought process.

I want to decouple the CSS and JS. Since there is no more pure HTML (now that we are in an SPA) the least modular thing we can do is separate JS and CSS.

Once we nest them, then we need to take care of npm updates, add unnecessary dependencies like react-bootstrap which are super unnecessary.  

The browser is insanely capable of linking and adding styles to our JS automatically. My reasoning is, this should not be Reacts task but the browsers task.

**Comment by kushal-arora-fw** [comment]
> > This change is interesting. Wondering why do we need CDN vs bundled in the app 🤔 Is it the bundle size we are worried of? Just want to understand the thought process.
> 
> I want to decouple the CSS and JS. Since there is no more pure HTML (now that we are in an SPA) the least modular thing we can do is separate JS and CSS.
> 
> Once we nest them, then we need to take care of npm updates, add unnecessary dependencies like react-bootstrap which are super unnecessary.
> 
> The browser is insanely capable of linking and adding styles to our JS automatically. My reasoning is, this should not be Reacts task but the browsers task.

hmm.. Interesting. I remember trying similar back in days before bootstrap 5 where it required jquery and other bundling dependencies. Guess now that they are no more needed, we can give it a shot. 👍

Point to note: It might take a bit on first load for caching.

**Review by kushal-arora-fw — APPROVED** [review]

**Review by Bottle7 — APPROVED** [review]

**Comment by antsand** [comment]
> 

Fair. We can download the CDN file into a asset folder and store it locally. This way it is only pulled form our servers. This should not affect speed. 
If we needed jquey, I would be doubtful.

**Comment by kushal-arora-fw** [comment]
Umm.. adding to asset - I doubt that would add a lot of value CDNs might have better access than our servers.. but the DNS for our server would be resolved. So.. looks like it might be relatively same. So, unless bundled as dependencies - I am open to either of the options.

And regarding jquery - agree we might not need as part of this project, but I was mentioning about Bootstrap prior to 5 needed it internally to allow their components to work properly like autopolute, pagination, etc.

**Comment by antsand** [comment]
> Umm.. adding to asset - I doubt that would add a lot of value CDNs might have better access than our servers.. but the DNS for our server would be resolved. So.. looks like it might be relatively same. So, unless bundled as dependencies - I am open to either of the options.
> 
> And regarding jquery - agree we might not need as part of this project, but I was mentioning about Bootstrap prior to 5 needed it internally to allow their components to work properly like autopolute, pagination, etc.

the size of bootstrap min is 191KB. Either ways it is fine. I don't accept the "speed" argument about SPA but we can always test it :)

**Comment by kushal-arora-fw** [comment]
> > Umm.. adding to asset - I doubt that would add a lot of value CDNs might have better access than our servers.. but the DNS for our server would be resolved. So.. looks like it might be relatively same. So, unless bundled as dependencies - I am open to either of the options.
> > And regarding jquery - agree we might not need as part of this project, but I was mentioning about Bootstrap prior to 5 needed it internally to allow their components to work properly like autopolute, pagination, etc.
> 
> the size of bootstrap min is 191KB. Either ways it is fine. I don't accept the "speed" argument about SPA but we can always test it :)

💯% in agreement to that!

**Pull request merged**
