### PR TITLE
Utopia-306: [Backend] Create PPQ schema and module structure

### PR DESCRIPTION
**Pull request by kushal-arora-fw**
# Description
~~Note: Please review and approve if looks good, but DO NOT MERGE yourself. Carefully observe the schema introduced. Did not find time to create a schema diagram. I want to discuss with the team before this gets in.~~ Decision - Static forms for now. Wiki to be updated for this. [UTOPIA-311](https://apps.itsm.gov.bc.ca/jira/browse/UTOPIA-311) created for this.

This PR includes the following proposed change(s):

- configured typeorm
- Added Migrations support
- Added helpful migration commands to Backend Readme
- Added PPQ schema [to be discussed]
- Added PPQ schema migration

Pending:
- Testing
- Endpoints (Utopia303,304]

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

Ran the migrations and all the newly added commands multiple times

## Development Dependency Working Agreement
- [ ] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [x] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [x] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [ ] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [ ] My code follows Airbnb React Style Guidelines

## API Development Changes
- [ ] N/A
- [x] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [ ] New and existing unit tests pass locally with my changes
- [x] My changes includes Swagger documentation updates that reflect the changes I am introducing

Swagger screenshot
image

### CODE REVIEW

**Review by akroon3r — APPROVED** [review]
I don't see anything on first pass.

**Comment by akroon3r** [comment]
Snyk is saying class-validator@0.13.2 has a vulnerability @kushal-arora-fw.

**Comment by kushal-arora-fw** [comment]
> Snyk is saying class-validator@0.13.2 has a vulnerability @kushal-arora-fw.

Strange! npm audit can't find it 🤔 @akroon3r 

image

However, it's only tagged at Snyk as Low Severity. More details [here](https://security.snyk.io/package/npm/class-validator)

Even though it is a low severity, I am looking for a fork and a specific version to NestJs [here](https://www.npmjs.com/package/@nestjs/class-transformer). will test few things and updating this PR. Thanks for the catch!

**Comment by kushal-arora-fw** [comment]
Snyk passed! I think we are good to go @akroon3r 💪

**Comment by kushal-arora-fw** [comment]
Merging it

**Pull request merged**
