### PR TITLE
[UTOPIA-854] [Refactor] [CollectionUseAndDisclosure]

### PR DESCRIPTION
**Pull request by kushal-arora-fw**
# Description

This PR includes the following proposed change(s):

- Refactoring Table and data inside CollectionUseAndDisclosure tab

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

## How Has This Been Tested?

Tested on app

## Development Dependency Working Agreement
- [x] My code DOES NOT include the importing of new dependencies into the DPIA ecosystem
- [ ] My code DOES include the importing of new dependencies into the DPIA ecosystem
**If new dependencies are being introduced to the DPIA ecosystem:**
- [ ] The functionality of the dependency drastically reduces code complexity and makes my changes more easily maintainable and readible 
- [ ] The dependency being introduced does not contain multiple layers of nested dependencies introducing maintainability complexity to the DPIA ecosystem

## Frontend Development Changes
- [ ] N/A
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to project documentation or diagrams that reflect my changes
- [ ] New and existing unit tests pass locally with my changes
- [x] My code follows Airbnb React Style Guidelines

## API Development Changes
- [x] N/A
- [ ] I have performed a self-review of my own code
- [ ] My code follows standards and practices outlined in the BC Government API Development Guidelines
- [ ] New and existing unit tests pass locally with my changes
- [ ] My changes includes Swagger documentation updates that reflect the changes I am introducing

## Definition of Done

Definition of Done

### CODE REVIEW

**Review by Bottle7 — APPROVED** [review]
🚀

**Comment by binggaofw** [comment]
missing step 1/2/3/4 for this 
Screen Shot 2023-03-09 at 11 03 00 AM

**Comment by kushal-arora-fw** [comment]
> missing step 1/2/3/4 for this Screen Shot 2023-03-09 at 11 03 00 AM

Good catch! It's just a key now for the columns. Adding it in a min.

**Comment by kushal-arora-fw** [comment]
Fixed @binggaofw

**Review by binggaofw — APPROVED** [review]

**Review by Bottle7 — APPROVED** [review]

**Review by antsand — APPROVED** [review]

**Pull request merged**
